cmake_minimum_required(VERSION 3.24)
project(OwlSightColor VERSION 0.2.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenColorIO 2.5.1 EXACT CONFIG REQUIRED)
add_executable(owlsight-ocio main.cpp)
target_include_directories(owlsight-ocio PRIVATE ../../../third_party/nlohmann)
target_compile_definitions(owlsight-ocio PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_link_libraries(owlsight-ocio PRIVATE OpenColorIO::OpenColorIO bcrypt)
if(MSVC)
  target_compile_options(owlsight-ocio PRIVATE /utf-8 /W4 /EHsc)
elseif(MINGW)
  target_compile_options(owlsight-ocio PRIVATE -Wall -Wextra -Wpedantic)
  target_link_options(owlsight-ocio PRIVATE -static)
endif()